//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArraysAtOne_Final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SENSOR_0001203B
    {
        public int Id { get; set; }
        public double temp { get; set; }
        public byte movement { get; set; }
        public System.DateTime time { get; set; }
    }
}
